// src/components/About.tsx
/*
 *   Copyright (c) 2024-2026. caoccao.com Sam Cao
 *   All rights reserved.

 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at

 *   http://www.apache.org/licenses/LICENSE-2.0

 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

import { useState, useEffect, useMemo, useRef } from 'react';
import {
  Box,
  FormControl,
  Link,
  MenuItem,
  Select,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Typography,
  TablePagination,
} from '@mui/material';

import { useAppStore } from '../lib/store';

const APP_NAME = 'BetterMediaInfo';

export default function About() {
  const [propertyFilter, setPropertyFilter] = useState('');
  const [debouncedPropertyFilter, setDebouncedPropertyFilter] = useState('');
  const [streamFilter, setStreamFilter] = useState<string | null>(null);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  const mediaInfoAbout = useAppStore((state) => state.mediaInfoAbout);
  const mediaInfoParameters = useAppStore((state) => state.mediaInfoParameters);
  const initAbout = useAppStore((state) => state.initAbout);
  const initParameters = useAppStore((state) => state.initParameters);

  useEffect(() => {
    initAbout();
    initParameters();
  }, [initAbout, initParameters]);

  // Debounce property filter
  useEffect(() => {
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }
    debounceRef.current = setTimeout(() => {
      setDebouncedPropertyFilter(propertyFilter);
    }, 200);

    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, [propertyFilter]);

  const streams = useMemo(() => {
    return [...new Set(mediaInfoParameters.map((parameter) => parameter.stream))];
  }, [mediaInfoParameters]);

  const filteredParameters = useMemo(() => {
    const propertyFilterLowerCased = debouncedPropertyFilter ? debouncedPropertyFilter.toLowerCase() : null;
    return mediaInfoParameters.filter((parameter) => {
      let hit = true;
      if (streamFilter !== null) {
        hit = parameter.stream === streamFilter;
      }
      if (hit && propertyFilterLowerCased) {
        hit = parameter.property.toLowerCase().includes(propertyFilterLowerCased);
      }
      return hit;
    });
  }, [mediaInfoParameters, streamFilter, debouncedPropertyFilter]);

  const handleChangePage = (_: unknown, newPage: number) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  // Reset page when filter changes
  useEffect(() => {
    setPage(0);
  }, [debouncedPropertyFilter, streamFilter]);

  const paginatedParameters = useMemo(() => {
    return filteredParameters.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage);
  }, [filteredParameters, page, rowsPerPage]);

  return (
    <Box sx={{ display: 'grid', gap: 2 }}>
      <Box sx={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: 1, alignItems: 'center' }}>
        <Typography variant="body2" sx={{ textAlign: 'right' }}>
          {APP_NAME}
        </Typography>
        <Typography variant="body2">v{mediaInfoAbout?.appVersion ?? ''}</Typography>

        <Typography variant="body2" sx={{ textAlign: 'right' }}>
          MediaInfoLib
        </Typography>
        <Typography variant="body2">
          v{mediaInfoAbout?.mediaInfoVersion.replace(/[^0-9.]+/g, '') ?? ''}
        </Typography>

        <Typography variant="body2" sx={{ textAlign: 'right' }}>
          Author
        </Typography>
        <Typography variant="body2">
          <Link href="https://github.com/caoccao" target="_blank" rel="noopener noreferrer">
            Sam Cao
          </Link>
        </Typography>

        <Typography variant="body2" sx={{ textAlign: 'right' }}>
          Github
        </Typography>
        <Typography variant="body2">
          <Link href="https://github.com/caoccao/BetterMediaInfo" target="_blank" rel="noopener noreferrer">
            https://github.com/caoccao/BetterMediaInfo
          </Link>
        </Typography>
      </Box>

      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
        <FormControl size="small" sx={{ minWidth: 120 }}>
          <Select
            value={streamFilter ?? ''}
            onChange={(e) => setStreamFilter(e.target.value || null)}
            displayEmpty
          >
            <MenuItem value="">All Streams</MenuItem>
            {streams.map((stream) => (
              <MenuItem key={stream} value={stream}>
                {stream}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
        <TextField
          placeholder="Property"
          value={propertyFilter}
          onChange={(e) => setPropertyFilter(e.target.value)}
          size="small"
          sx={{ flex: 1 }}
        />
      </Box>

      <TableContainer>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell sx={{ bgcolor: 'success.light', color: 'success.contrastText', fontWeight: 'bold' }}>
                ID
              </TableCell>
              <TableCell sx={{ bgcolor: 'success.light', color: 'success.contrastText', fontWeight: 'bold' }}>
                Stream
              </TableCell>
              <TableCell sx={{ bgcolor: 'success.light', color: 'success.contrastText', fontWeight: 'bold' }}>
                Property
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {paginatedParameters.map((parameter) => (
              <TableRow key={parameter.id}>
                <TableCell>{parameter.id}</TableCell>
                <TableCell>{parameter.stream}</TableCell>
                <TableCell>{parameter.property}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      <TablePagination
        component="div"
        count={filteredParameters.length}
        page={page}
        onPageChange={handleChangePage}
        rowsPerPage={rowsPerPage}
        onRowsPerPageChange={handleChangeRowsPerPage}
        rowsPerPageOptions={[10, 15, 20]}
        size="small"
      />
    </Box>
  );
}

// src/routes/about.svelte
<script lang="ts">
  /*
 	 *   Copyright (c) 2024. caoccao.com Sam Cao
 	 *   All rights reserved.

 	 *   Licensed under the Apache License, Version 2.0 (the "License");
 	 *   you may not use this file except in compliance with the License.
 	 *   You may obtain a copy of the License at

 	 *   http://www.apache.org/licenses/LICENSE-2.0

 	 *   Unless required by applicable law or agreed to in writing, software
 	 *   distributed under the License is distributed on an "AS IS" BASIS,
 	 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	 *   See the License for the specific language governing permissions and
 	 *   limitations under the License.
 	 */
  import { onMount } from "svelte";
  import { MenuField, Paginate, Pagination, Table, TextField } from "svelte-ux";
  import type { MenuOption } from "svelte-ux";
  import * as Protocol from "../lib/protocol";
  import { mediaInfoAbout, mediaInfoParameters } from "../lib/store";

  const APP_NAME = "Better Media Info";
  let about = { appVersion: "", mediaInfoVersion: "" };
  let filteredParameters: Array<Protocol.Parameter> = [];
  let parameters: Array<Protocol.Parameter> = [];
  let propertyFilter: string | null = null;
  let streamFilter: string | null = null;
  let streams: Array<MenuOption> = [];

  $: {
    const propertyFilterLowerCased = propertyFilter
      ? propertyFilter.toLowerCase()
      : null;
    filteredParameters = parameters.filter((parameter) => {
      let hit = true;
      if (streamFilter !== null) {
        hit = parameter.stream === streamFilter;
      }
      if (hit && propertyFilter) {
        hit = parameter.property
          .toLocaleLowerCase()
          .includes(propertyFilterLowerCased as string);
      }
      return hit;
    });
    streams = [
      ...new Set(parameters.map((parameter) => parameter.stream)).values(),
    ].map((stream) => ({ label: stream, value: stream }));
  }

  onMount(async () => {
    mediaInfoAbout.subscribe((value) => {
      about = value;
    });
    mediaInfoParameters.subscribe((value) => {
      parameters = value;
    });
  });
</script>

<div class="grid">
  <div>
    <p>{APP_NAME} - v{about.appVersion}</p>
    <p>{about.mediaInfoVersion}</p>
    <p>
      Author -
      <a
        href="https://github.com/caoccao"
        target="_blank"
        class="text-blue-600 visited:text-purple-600 underline underline-offset-auto"
        >Sam Cao</a
      >
    </p>
  </div>
  <div class="my-3 grid grid-flow-col grid-cols-[auto,1fr] gap-2">
    <MenuField
      classes={{
        root: "min-w-32 max-w-32",
      }}
      options={[{ label: "All Streams", value: null }, ...streams]}
      bind:value={streamFilter}
    />
    <TextField placeholder="Property" bind:value={propertyFilter} />
  </div>
  <Paginate
    data={filteredParameters}
    perPage={10}
    let:pageData={pagedParameters}
    let:pagination={paginator}
  >
    <Table
      data={pagedParameters}
      classes={{
        table: "border-collapse border border-slate-500",
        th: "border border-slate-600 p-2 bg-lime-50",
        td: "border border-slate-700 p-2",
      }}
      columns={[
        {
          name: "id",
          header: "ID",
          align: "left",
          format: "integer",
        },
        {
          name: "stream",
          header: "Stream",
          align: "left",
        },
        {
          name: "property",
          header: "Property",
          align: "left",
        },
      ]}
    />
    <Pagination
      pagination={paginator}
      perPageOptions={[10, 15, 20]}
      show={[
        "perPage",
        "pagination",
        "firstPage",
        "prevPage",
        "nextPage",
        "lastPage",
      ]}
      classes={{
        root: "border-t py-1 mt-2",
        perPage: "flex-1 text-right",
        pagination: "px-8",
      }}
    />
  </Paginate>
</div>
