// src/components/Config.tsx
/*
 *   Copyright (c) 2024-2026. caoccao.com Sam Cao
 *   All rights reserved.

 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at

 *   http://www.apache.org/licenses/LICENSE-2.0

 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

import { useState, useEffect, useRef } from 'react';
import {
  Box,
  Button,
  FormControl,
  FormControlLabel,
  MenuItem,
  Radio,
  RadioGroup,
  Select,
  TextField,
  Typography,
} from '@mui/material';
import { useTranslation } from 'react-i18next';
import * as Protocol from '../lib/protocol';
import { setConfig as saveConfig } from '../lib/service';
import { useAppStore } from '../lib/store';
import { changeLanguage } from '../i18n';

export default function Config() {
  const { t } = useTranslation();
  const [appendOnFileDrop, setAppendOnFileDrop] = useState(true);
  const [bitRatePrecision, setBitRatePrecision] = useState<Protocol.FormatPrecision>(
    Protocol.FormatPrecision.Two
  );
  const [bitRateUnit, setBitRateUnit] = useState<Protocol.FormatUnit>(
    Protocol.FormatUnit.KMGT
  );
  const [sizePrecision, setSizePrecision] = useState<Protocol.FormatPrecision>(
    Protocol.FormatPrecision.Two
  );
  const [sizeUnit, setSizeUnit] = useState<Protocol.FormatUnit>(
    Protocol.FormatUnit.KMGT
  );
  const [displayMode, setDisplayMode] = useState<Protocol.DisplayMode>(Protocol.DisplayMode.Auto);
  const [language, setLanguage] = useState<Protocol.Language>(Protocol.Language.EnUS);
  const [directoryMode, setDirectoryMode] = useState<Protocol.ConfigDirectoryMode>(
    Protocol.ConfigDirectoryMode.All
  );
  const [fileExtensionsAudio, setFileExtensionsAudio] = useState('');
  const [fileExtensionsImage, setFileExtensionsImage] = useState('');
  const [fileExtensionsVideo, setFileExtensionsVideo] = useState('');
  const [isDirty, setIsDirty] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const isInitializedRef = useRef(false);

  const config = useAppStore((state) => state.config);
  const setStoreConfig = useAppStore((state) => state.setConfig);
  const setDialogNotification = useAppStore((state) => state.setDialogNotification);

  // Initialize from config only once
  useEffect(() => {
    if (config && config.fileExtensions && !isInitializedRef.current) {
      isInitializedRef.current = true;
      setAppendOnFileDrop(config.appendOnFileDrop);
      setBitRatePrecision(config.bitRate?.precision ?? Protocol.FormatPrecision.Two);
      setBitRateUnit(config.bitRate?.unit ?? Protocol.FormatUnit.KMGT);
      setSizePrecision(config.size?.precision ?? Protocol.FormatPrecision.Two);
      setSizeUnit(config.size?.unit ?? Protocol.FormatUnit.KMGT);
      setDisplayMode(config.displayMode);
      setLanguage(config.language ?? Protocol.Language.EnUS);
      setDirectoryMode(config.directoryMode);
      setFileExtensionsAudio(config.fileExtensions.audio?.join(', ') ?? '');
      setFileExtensionsImage(config.fileExtensions.image?.join(', ') ?? '');
      setFileExtensionsVideo(config.fileExtensions.video?.join(', ') ?? '');
    }
  }, [config]);

  // Reset initialization flag when component unmounts so it reinitializes on next mount
  useEffect(() => {
    return () => {
      isInitializedRef.current = false;
    };
  }, []);

  // Debounced file extension changes with 200ms delay
  const handleFileExtensionChange = (
    setter: React.Dispatch<React.SetStateAction<string>>,
    value: string
  ) => {
    setter(value);
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }
    debounceRef.current = setTimeout(() => {
      setIsDirty(true);
    }, 200);
  };

  const handleChange = () => {
    setIsDirty(true);
  };

  const convertFileExtensions = (fileExtensions: string): string[] => {
    return fileExtensions
      .split(/[, .]+/g)
      .filter((extension) => extension.length > 0);
  };

  const createConfig = (): Protocol.Config => ({
    appendOnFileDrop,
    bitRate: {
      precision: bitRatePrecision,
      unit: bitRateUnit,
    },
    displayMode,
    directoryMode,
    fileExtensions: {
      audio: convertFileExtensions(fileExtensionsAudio),
      image: convertFileExtensions(fileExtensionsImage),
      video: convertFileExtensions(fileExtensionsVideo),
    },
    language,
    size: {
      precision: sizePrecision,
      unit: sizeUnit,
    },
  });

  const handleSave = async () => {
    try {
      const newConfig = await saveConfig(createConfig());
      setStoreConfig(newConfig);
      changeLanguage(newConfig.language);
      setIsDirty(false);
      setDialogNotification({
        title: t('config.settingsSaved'),
        type: Protocol.DialogNotificationType.Info,
      });
    } catch (error) {
      setDialogNotification({
        title: error ? error.toString() : t('config.settingsSaveError'),
        type: Protocol.DialogNotificationType.Error,
      });
    }
  };

  // Update store immediately when displayMode changes (for instant theme switching)
  useEffect(() => {
    if (config && isInitializedRef.current && displayMode !== config.displayMode) {
      setStoreConfig({ ...config, displayMode });
    }
  }, [displayMode, config, setStoreConfig]);

  return (
    <Box sx={{ display: 'grid', gap: 2 }}>
      <Box>
        <Typography variant="subtitle1" sx={{ fontWeight: 'bold', pb: 1, borderBottom: 2, borderColor: 'success.main' }}>
          {t('config.title')}
        </Typography>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.appearance')}
        </Typography>
        <FormControl sx={{ mt: 1 }}>
          <RadioGroup
            row
            value={displayMode}
            onChange={(e) => {
              setDisplayMode(e.target.value as Protocol.DisplayMode);
              handleChange();
            }}
          >
            <FormControlLabel
              value={Protocol.DisplayMode.Auto}
              control={<Radio size="small" />}
              label={<Typography variant="body2">{t('config.autoMode')}</Typography>}
            />
            <FormControlLabel
              value={Protocol.DisplayMode.Light}
              control={<Radio size="small" />}
              label={<Typography variant="body2">{t('config.lightMode')}</Typography>}
            />
            <FormControlLabel
              value={Protocol.DisplayMode.Dark}
              control={<Radio size="small" />}
              label={<Typography variant="body2">{t('config.darkMode')}</Typography>}
            />
          </RadioGroup>
        </FormControl>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.language')}
        </Typography>
        <FormControl size="small" sx={{ mt: 1, minWidth: 150 }}>
          <Select
            value={language}
            onChange={(e) => {
              setLanguage(e.target.value as Protocol.Language);
              handleChange();
            }}
          >
            {Protocol.getLanguages().map((lang) => (
              <MenuItem key={lang} value={lang}>
                {Protocol.getLanguageLabel(lang)}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.appendOnFileDrop')}
        </Typography>
        <FormControl sx={{ mt: 1 }}>
          <RadioGroup
            row
            value={appendOnFileDrop.toString()}
            onChange={(e) => {
              setAppendOnFileDrop(e.target.value === 'true');
              handleChange();
            }}
          >
            <FormControlLabel
              value="true"
              control={<Radio size="small" />}
              label={<Typography variant="body2">{t('config.append')}</Typography>}
            />
            <FormControlLabel
              value="false"
              control={<Radio size="small" />}
              label={<Typography variant="body2">{t('config.doNotAppend')}</Typography>}
            />
          </RadioGroup>
        </FormControl>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.directoryMode')}
        </Typography>
        <FormControl size="small" sx={{ mt: 1, minWidth: 120 }}>
          <Select
            value={directoryMode}
            onChange={(e) => {
              setDirectoryMode(e.target.value as Protocol.ConfigDirectoryMode);
              handleChange();
            }}
          >
            {Protocol.getConfigDirectoryModes().map((mode) => (
              <MenuItem key={mode} value={mode}>
                {mode}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.fileExtensions')}
        </Typography>
        <Box sx={{ display: 'grid', gap: 1.5, mt: 1 }}>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.audioFileExtensions')}
            </Typography>
            <TextField
              value={fileExtensionsAudio}
              onChange={(e) => handleFileExtensionChange(setFileExtensionsAudio, e.target.value)}
              size="small"
              fullWidth
            />
          </Box>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.imageFileExtensions')}
            </Typography>
            <TextField
              value={fileExtensionsImage}
              onChange={(e) => handleFileExtensionChange(setFileExtensionsImage, e.target.value)}
              size="small"
              fullWidth
            />
          </Box>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.videoFileExtensions')}
            </Typography>
            <TextField
              value={fileExtensionsVideo}
              onChange={(e) => handleFileExtensionChange(setFileExtensionsVideo, e.target.value)}
              size="small"
              fullWidth
            />
          </Box>
        </Box>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.bitRate')}
        </Typography>
        <Box sx={{ display: 'flex', gap: 2, mt: 1 }}>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.precision')}
            </Typography>
            <FormControl size="small" sx={{ display: 'block', mt: 0.5, minWidth: 100 }}>
              <Select
                value={bitRatePrecision}
                onChange={(e) => {
                  setBitRatePrecision(e.target.value as Protocol.FormatPrecision);
                  handleChange();
                }}
              >
                {Protocol.getFormatPrecisions().map((p) => (
                  <MenuItem key={p} value={p}>
                    {Protocol.getFormatPrecisionLabel(p)}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.unit')}
            </Typography>
            <FormControl size="small" sx={{ display: 'block', mt: 0.5, minWidth: 120 }}>
              <Select
                value={bitRateUnit}
                onChange={(e) => {
                  setBitRateUnit(e.target.value as Protocol.FormatUnit);
                  handleChange();
                }}
              >
                {Protocol.getFormatUnits().map((u) => (
                  <MenuItem key={u} value={u}>
                    {Protocol.getFormatUnitLabel(u)}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
        </Box>
      </Box>

      <Box>
        <Typography variant="subtitle2" sx={{ fontWeight: 'medium', pb: 1, borderBottom: 1, borderColor: 'success.light' }}>
          {t('config.size')}
        </Typography>
        <Box sx={{ display: 'flex', gap: 2, mt: 1 }}>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.precision')}
            </Typography>
            <FormControl size="small" sx={{ display: 'block', mt: 0.5, minWidth: 100 }}>
              <Select
                value={sizePrecision}
                onChange={(e) => {
                  setSizePrecision(e.target.value as Protocol.FormatPrecision);
                  handleChange();
                }}
              >
                {Protocol.getFormatPrecisions().map((p) => (
                  <MenuItem key={p} value={p}>
                    {Protocol.getFormatPrecisionLabel(p)}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
          <Box>
            <Typography variant="caption" color="text.secondary">
              {t('config.unit')}
            </Typography>
            <FormControl size="small" sx={{ display: 'block', mt: 0.5, minWidth: 120 }}>
              <Select
                value={sizeUnit}
                onChange={(e) => {
                  setSizeUnit(e.target.value as Protocol.FormatUnit);
                  handleChange();
                }}
              >
                {Protocol.getFormatUnits().map((u) => (
                  <MenuItem key={u} value={u}>
                    {Protocol.getFormatUnitLabel(u)}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
        </Box>
      </Box>

      <Box sx={{ display: 'flex', justifyContent: 'center', mt: 1 }}>
        <Button variant="contained" color="primary" disabled={!isDirty} onClick={handleSave} sx={{ minWidth: 150 }}>
          {t('config.save')}
        </Button>
      </Box>
    </Box>
  );
}

// src/routes/config.svelte
<script lang="ts">
  /*
 	 *   Copyright (c) 2024-2025. caoccao.com Sam Cao
 	 *   All rights reserved.

 	 *   Licensed under the Apache License, Version 2.0 (the "License");
 	 *   you may not use this file except in compliance with the License.
 	 *   You may obtain a copy of the License at

 	 *   http://www.apache.org/licenses/LICENSE-2.0

 	 *   Unless required by applicable law or agreed to in writing, software
 	 *   distributed under the License is distributed on an "AS IS" BASIS,
 	 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 	 *   See the License for the specific language governing permissions and
 	 *   limitations under the License.
 	 */

  import { onDestroy, onMount } from "svelte";
  import {
    Button,
    MenuField,
    Radio,
    TableOfContents,
    TextField,
  } from "svelte-ux";
  import * as Protocol from "../lib/protocol";
  import { setConfig } from "../lib/service";
  import { config, dialogNotification, isConfigDirty } from "../lib/store";

  const CSS_CLASS_H1 = "text-lg font-bold py-2 border-b-2 border-b-lime-400";
  const CSS_CLASS_H2 = "text-base font-medium py-2 border-b border-b-lime-300";
  const CSS_CLASS_H3 = "text-sm";

  let appendOnFileDrop: boolean = true;
  let directoryMode: Protocol.ConfigDirectoryMode =
    Protocol.ConfigDirectoryMode.All;
  let fileExtensionsAudio: string = "";
  let fileExtensionsImage: string = "";
  let fileExtensionsVideo: string = "";
  let isDirty = false;

  onDestroy(() => {
    try {
      let newConfig = createConfig();
      config.set(newConfig);
    } catch (error) {
      console.error(error);
    }
  });

  onMount(() => {
    config.subscribe((value) => {
      if (value) {
        appendOnFileDrop = value.appendOnFileDrop;
        directoryMode = value.directoryMode;
        fileExtensionsAudio = value.fileExtensions.audio.join(", ");
        fileExtensionsImage = value.fileExtensions.image.join(", ");
        fileExtensionsVideo = value.fileExtensions.video.join(", ");
      }
    });
    isConfigDirty.subscribe((value) => {
      isDirty = value;
    });
  });

  function createConfig(): Protocol.Config {
    return {
      appendOnFileDrop: appendOnFileDrop,
      directoryMode: directoryMode,
      fileExtensions: {
        audio: convertFileExtensions(fileExtensionsAudio),
        image: convertFileExtensions(fileExtensionsImage),
        video: convertFileExtensions(fileExtensionsVideo),
      },
    };
  }

  function convertFileExtensions(fileExtensions: string): string[] {
    return fileExtensions
      .split(/[, \.]+/g)
      .filter((extension) => extension.length > 0);
  }

  function onChange() {
    isConfigDirty.set(true);
  }

  async function onClickSave(event: MouseEvent) {
    event.stopPropagation();
    try {
      config.set(await setConfig(createConfig()));
      isConfigDirty.set(false);
      dialogNotification.set({
        title: "Settings saved.",
        type: Protocol.DialogNotificationType.Info,
      });
    } catch (error) {
      dialogNotification.set({
        title: error
          ? error.toString()
          : "Failed to save settings with unknown error.",
        type: Protocol.DialogNotificationType.Error,
      });
    }
  }
</script>

<div class="grid gap-2">
  <div class="grid grid-flow-col grid-cols-[auto,1fr] gap-2">
    <TableOfContents element="#config" />
    <div id="config" class="grid gap-2">
      <h1 class={CSS_CLASS_H1}>Settings</h1>
      <h2 class={CSS_CLASS_H2}>Append on File Drop</h2>
      <div class="flex gap-4">
        <Radio
          name="appendOnFileDrop"
          bind:group={appendOnFileDrop}
          value={true}
          on:change={onChange}
        >
          Append
        </Radio>
        <Radio
          name="appendOnFileDrop"
          bind:group={appendOnFileDrop}
          value={false}
          on:change={onChange}
        >
          Do not append
        </Radio>
      </div>
      <h2 class={CSS_CLASS_H2}>Directory Mode</h2>
      <MenuField
        classes={{
          root: "min-w-32 max-w-32",
        }}
        options={Protocol.getConfigDirectoryModes().map((mode) => ({
          label: mode,
          value: mode,
        }))}
        bind:value={directoryMode}
        on:change={onChange}
      ></MenuField>
      <h2 class={CSS_CLASS_H2}>File Extensions</h2>
      <h3 class={CSS_CLASS_H3}>Audio File Extensions</h3>
      <TextField bind:value={fileExtensionsAudio} on:change={onChange} />
      <h3 class={CSS_CLASS_H3}>Image File Extensions</h3>
      <TextField bind:value={fileExtensionsImage} on:change={onChange} />
      <h3 class={CSS_CLASS_H3}>Video File Extensions</h3>
      <TextField bind:value={fileExtensionsVideo} on:change={onChange} />
    </div>
  </div>
  <Button
    variant="fill-light"
    color="primary"
    classes={{ root: "w-48 justify-self-center" }}
    disabled={!isDirty}
    on:click={onClickSave}
  >
    Save
  </Button>
</div>
